### ISSUE TITLE
PHP4 style constructors deprecated in WordPress 4.3

### ISSUE THREAD

**Issue by webstractions** [justintadlock/widgets-reloaded#2]
You are probably aware of that PHP4 constructors are deprecated, but thought I would create an issue as a gentle reminder.

Code throwing the warning is common to all of the `widget-x.php` include files, where:

```
class Hybrid_Widget_Archives extends WP_Widget {
   ...
   function __construct() {
      ...
      $this->WP_Widget(        <---- use parent::__construct here I think
         'hybrid-archives',
         __( 'Archives', 'widgets-reloaded' ),
        $widget_options,
        $control_options
     );
     ...
   }
}
```

I am just guessing that `parent::__construct` will fix the warning. I have not tried it yet.

**Comment by justintadlock** [comment]
Yep, I know.  These notices will get cleaned up in the next update.

**Comment by lkraav** [comment]
Yeah, `sed -i 's/$this->WP_Widget/parent::__construct/g' widget*` does the trick.

@justintadlock will older `hybrid-core` branches also gain this cleanup?

**Comment by justintadlock** [comment]
No, they won't. Theme authors should update. :)

**Comment by lkraav** [comment]
For general market themes, sure. For businesses served with customs, upgrading is not so trivial because of losing `$prefix`. I guess it could be charged as some kind of maintenance fee, but few would be willing to pay for it with a smile as a separate line item, as it doesn't add any new value.

I'll just maintain a simple patch myself and push a `hybrid-core-1.6` update.

**Comment by lkraav** [comment]
Why not 0.6.1 with just this change?

**Comment by justintadlock** [comment]
Just closing this as fixed.
